ALTER TABLE users ADD COLUMN public_key TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN wrapped_private_key TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN key_wrap_salt TEXT NOT NULL DEFAULT '';
